<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('PollOptionVote', 'doctrine');

/**
 * BasePollOptionVote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $option_id
 * @property integer $user_id
 * @property string $ip
 * @property timestamp $created_at
 * @property PollOption $PollOption
 * 
 * @method integer        getId()         Returns the current record's "id" value
 * @method integer        getOptionId()   Returns the current record's "option_id" value
 * @method integer        getUserId()     Returns the current record's "user_id" value
 * @method string         getIp()         Returns the current record's "ip" value
 * @method timestamp      getCreatedAt()  Returns the current record's "created_at" value
 * @method PollOption     getPollOption() Returns the current record's "PollOption" value
 * @method PollOptionVote setId()         Sets the current record's "id" value
 * @method PollOptionVote setOptionId()   Sets the current record's "option_id" value
 * @method PollOptionVote setUserId()     Sets the current record's "user_id" value
 * @method PollOptionVote setIp()         Sets the current record's "ip" value
 * @method PollOptionVote setCreatedAt()  Sets the current record's "created_at" value
 * @method PollOptionVote setPollOption() Sets the current record's "PollOption" value
 * 
 * @package    imdb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePollOptionVote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('poll_option_vote');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('option_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ip', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PollOption', array(
             'local' => 'option_id',
             'foreign' => 'id'));
    }
}