<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoryContent', 'doctrine');

/**
 * BaseCategoryContent
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $category_id
 * @property integer $content_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_aid
 * @property integer $updated_aid
 * @property Admin $Admin
 * @property Category $Category
 * @property Content $Content
 * @property Admin $Admin_4
 * 
 * @method integer         getId()          Returns the current record's "id" value
 * @method integer         getCategoryId()  Returns the current record's "category_id" value
 * @method integer         getContentId()   Returns the current record's "content_id" value
 * @method timestamp       getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp       getUpdatedAt()   Returns the current record's "updated_at" value
 * @method integer         getCreatedAid()  Returns the current record's "created_aid" value
 * @method integer         getUpdatedAid()  Returns the current record's "updated_aid" value
 * @method Admin           getAdmin()       Returns the current record's "Admin" value
 * @method Category        getCategory()    Returns the current record's "Category" value
 * @method Content         getContent()     Returns the current record's "Content" value
 * @method Admin           getAdmin4()      Returns the current record's "Admin_4" value
 * @method CategoryContent setId()          Sets the current record's "id" value
 * @method CategoryContent setCategoryId()  Sets the current record's "category_id" value
 * @method CategoryContent setContentId()   Sets the current record's "content_id" value
 * @method CategoryContent setCreatedAt()   Sets the current record's "created_at" value
 * @method CategoryContent setUpdatedAt()   Sets the current record's "updated_at" value
 * @method CategoryContent setCreatedAid()  Sets the current record's "created_aid" value
 * @method CategoryContent setUpdatedAid()  Sets the current record's "updated_aid" value
 * @method CategoryContent setAdmin()       Sets the current record's "Admin" value
 * @method CategoryContent setCategory()    Sets the current record's "Category" value
 * @method CategoryContent setContent()     Sets the current record's "Content" value
 * @method CategoryContent setAdmin4()      Sets the current record's "Admin_4" value
 * 
 * @package    imdb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoryContent extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category_content');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('category_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('content_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0000-00-00 00:00:00',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_aid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_aid', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Admin', array(
             'local' => 'created_aid',
             'foreign' => 'id'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id'));

        $this->hasOne('Content', array(
             'local' => 'content_id',
             'foreign' => 'id'));

        $this->hasOne('Admin as Admin_4', array(
             'local' => 'updated_aid',
             'foreign' => 'id'));
    }
}