<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/24 08:02:49
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_host' => 'http://localhost/nytimes/web/',
  'app_webname' => 'baavar.mn | Өдөр тутмын вэб сэтгүүл',
  'app_feedbackmail' => 'info@baavar.mn',
  'app_pager' => 20,
  'app_limit' => 20,
));
