<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/07/24 05:40:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=nytimes',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
