<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/07/25 03:19:08
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
