<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/07/24 16:46:38
$this->security = array (
  'login' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
