<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/07/24 17:02:58
sfConfig::add(array(
  'app_sfImageTransformPlugin_default_adapter' => 'GD',
  'app_sfImageTransformPlugin_default_image' => array (
  'mime_type' => 'image/png',
  'filename' => 'Untitled.png',
  'width' => 100,
  'height' => 100,
  'color' => '#FFFFFF',
),
  'app_sfImageTransformPlugin_font_dir' => '/usr/share/fonts/truetype/msttcorefonts',
  'app_sfImageTransformPlugin_mime_type' => array (
  'auto_detect' => true,
  'library' => 'gd_mime_type',
),
  'app_host' => 'http://localhost/nytimes/web/',
  'app_webname' => 'Спорт мэдээ - Монголын болон Дэлхий дахины спортын мэдээ мэдээлэл',
  'app_domain' => 'sport.mn',
  'app_domain_www' => 'www.sport.mn',
  'app_feedback_email' => 'batsukhd.mn@gmail.com',
  'app_facebook' => 'sport.mn',
  'app_twitter' => 'sport_mn',
  'app_youtube' => 'sport_mn',
  'app_pager' => 20,
  'app_limit' => 20,
  'app_nb_comment' => 20,
));
