<?php
// auto-generated by sfCacheConfigHandler
// date: 2015/07/26 05:45:17
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

