<?php
// auto-generated by sfCacheConfigHandler
// date: 2015/07/22 10:37:01
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

