<?php
// auto-generated by sfCacheConfigHandler
// date: 2015/07/24 08:33:57
$this->addCache($moduleName, 'DEFAULT', array('withLayout' => false, 'lifeTime' => 0, 'clientLifeTime' => 0, 'contextual' => false, 'vary' => array ()));

