Монголын нэгдсэн кино сан# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        baavar.mn | Өдөр тутмын вэб сэтгүүл
    description:  baavar.mn | Өдөр тутмын вэб сэтгүүл
    keywords:     baavar.mn | Өдөр тутмын вэб сэтгүүл
    language:     en
    robots:       index, follow

  stylesheets:    [admin.css]

  javascripts:    []

  has_layout:     true
  layout:         layout