<?php

/**
 * CategoryContentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryContentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryContentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoryContent');
    }
}