<?php

/**
 * CommentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CommentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Comment');
    }
    
    public function updateNbLove($id, $nbLove)
    {
        $q = Doctrine_Query::create()->update('Comment')
            ->set('nb_love', $nbLove)
            ->where('id = ?', $id)
            ->execute();
    }
    
    private function params($q, $params = array())
    {
        $q->from('Comment');
  
        if(isset($params['id']) && $params['id'] != null)
            $q->andWhere('id= ?', $params['id']);
        
        if(isset($params['ids']) && $params['ids'] != null)
            $q->andWhereIn('id', $params['ids']);
                
        if(isset($params['objectType']) && $params['objectType'] != null)
            $q->andWhere('object_type= ?', $params['objectType']);
            
        if(isset($params['objectId']) && $params['objectId'] != null)
            $q->andWhere('object_id= ?', $params['objectId']);
            
        if(isset($params['name']) && $params['name'] != null)
            $q->andWhere('name= ?', $params['name']);
            
        if(isset($params['ip_address']) && $params['ip_address'] != null)
            $q->andWhere('ip_address= ?', $params['ip_address']);
            
        if(isset($params['text']) && $params['text'])
            $q->andWhere('text= ?', $params['text']);

        if(isset($params['keyword']) && $params['keyword'])
            $q->andWhere('text LIKE ? OR name LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));

        # isActive
        if(isset($params['isActive'])) {
            if($params['isActive'] != "all" && in_array($params['isActive'], array('0', '1'))) {
                $q->andWhere('is_active = ?', $params['isActive']);
            }
        } else {
            $q->andWhere('is_active = ?', 1);
        }

        // group, offset, limit, order
        if(isset($params['groupBy']) && $params['groupBy'])
            $q->groupBy($params['groupBy']);        

        if(isset($params['offset']) && $params['offset'])
            $q->offset($params['offset']);
        
        $limit = isset($params['limit']) ? $params['limit'] : sfConfig::get('app_limit', 30);
        $q->limit($limit);
  
        $order = isset($params['orderBy']) ? $params['orderBy'] : 'created_at ASC';
        $q->orderBy($order);

        return $q;
    }
    
    public static function doExecute($columns = array(), $params = array())
    {
        $q = Doctrine_Query::create()->select(join(',', $columns));
        $q = self::params($q, $params);
        return $q->execute();
    }
    
  
    public static function doFetchArray($columns = array(), $params = array())
    {
        $q = Doctrine_Query::create()->select(join(',', $columns));
        $q = self::params($q, $params);
        return $q->fetchArray();
    }
    
    
    public static function doFetchSelection($fieldName, $columns = array(), $params = array())
    {
        $res = array();
        $rss = self::doFetchArray($columns, $params);
        foreach ($rss as $rs) 
        {
            $res[$rs['id']] = $rs[$fieldName];
        }
        return $res;
    }
    
    public static function doFetchOne($columns = array(), $params = array())
    {
        $q = Doctrine_Query::create()->select(join(',', $columns));
        $params['limit'] = 1;
        $q = self::params($q, $params);
        return $q->fetchOne();
    }
    
    
    public static function getPager($columns = array(), $params = array(), $page=1)
    {
        $q = Doctrine_Query::create()->select(join(',', $columns));
        $q = self::params($q, $params);

        $pager = new sfDoctrinePager(sfConfig::get('app_pager', 30));
        $pager->setPage(GlobalLib::clearInput(intval($page)));
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
  
    public static function doCount($params = array())
    {
        $q = Doctrine_Query::create()->select('count(id)');
        $q = self::params($q, $params);
        return $q->count();
    }
    
}