<?php

/**
 * Content
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    imdb
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Content extends BaseContent
{
    public function __toString() {
        return $this->getTitle();
    }
    
    public function getCategoryIds() {
        $categoryIds = array();
        foreach ($this->getCategoryContent() as $categoryContent) {
            $categoryIds[] = $categoryContent->getCategoryId();
        }
        return $categoryIds;
    }
    
    public function getCategoryNames() {
        $categoryNames = array();
        foreach ($this->getCategoryContent() as $categoryContent) {
            $categoryNames[] = $categoryContent->getCategory()->getName();
        }
        return $categoryNames;
    }
}