<?php

/**
 * PollTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Poll');
    }
    
    public function updateContentId($contentId, $id)
    {
        $q = Doctrine_Query::create()->update('Poll')
            ->set('content_id', $contentId)
            ->where('id = ?', $id)
            ->execute();
    }
    
    public function doExecute($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        
        return $q->execute();
    }
    
  
    public function doFetchArray($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        return $q->fetchArray();
    }
    
    
    public function doFetchSelection($params = array())
    {
        $res = array();
        $rss = self::doFetchArray($params);
        foreach ($rss as $rs)
        {
          $res[$rs['id']] = $rs['title'];
        }
        return $res;
    }
  
    
    public function doFetchOne($params = array())
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
        return $q->fetchOne();
    }
    
  
    public function doCount($params = array())
    {
        $q = Doctrine_Query::create()->select('count(id)');
        $q = self::params($q, $params);
        return $q->count();
    }
    
    public function getPager($params = array(), $page=1)
    {
        $q = Doctrine_Query::create()->select('*');
        $q = self::params($q, $params);
                
        $pager = new sfDoctrinePager('Poll', sfConfig::get('app_pager', 30));
        $pager->setPage($page);
        $pager->setQuery($q);
        $pager->init();
        
        return $pager;
    }
    
    
    private function params($q, $params = array())
    {
        $q->from('Poll');
  
        if(isset($params['id']) && $params['id'] != null)
            $q->andWhere('id= ?', $params['id']);
            
        if(isset($params['route']) && $params['route'] != null)
            $q->andWhere('route= ?', $params['route']);
            
        // quiz <=> content 2taldaa holbolt hiilee
        if(isset($params['contentId']) && $params['contentId'] != null)
            $q->andWhere('content_id = ?', $params['contentId']);
        
        if(isset($params['keyword']) && $params['keyword'])
            $q->andWhere('title LIKE ? or body LIKE ?', array('%'.$params['keyword'].'%', '%'.$params['keyword'].'%'));
            
        if(isset($params['multipleChoice']) && $params['multipleChoice'] != null)
            $q->andWhere('multiple_choice = ?', $params['multipleChoice']);
            
        if(isset($params['optionsAddable']) && $params['optionsAddable'] != null)
            $q->andWhere('options_addable = ?', $params['optionsAddable']);

        if(isset($params['isFeatured']) && $params['isFeatured'] != null)
            $q->andWhere('is_featured = ?', $params['isFeatured']);
        
        // is_active
        if(isset($params['isActive'])) {
            if($params['isActive'] != "all" && in_array($params['isActive'], array('0', '1'))) // all ued filter hiihgui
                $q->andWhere('is_active = ?', $params['isActive']);
        } else {
            $q->andWhere('is_active = ?', 1); // default
        }

        // group, offset, limit, order
        if(isset($params['groupBy']) && $params['groupBy'])
            $q->groupBy($params['groupBy']);        

        if(isset($params['offset']) && $params['offset'])
            $q->offset($params['offset']);
        
        $limit = isset($params['limit']) ? $params['limit'] : sfConfig::get('app_limit', 30);
        $q->limit($limit);
  
        $order = isset($params['orderBy']) ? $params['orderBy'] : 'sort DESC, created_at DESC';
        $q->orderBy($order);

        return $q;
    }
}