<?php

/**
 * PollOptionVoteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PollOptionVoteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PollOptionVoteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PollOptionVote');
    }
}