_banner:
  enabled:     true

_bannerHome:
  enabled:     true
  
_bannerMiddle:
  enabled:     true

_category:
  enabled:     true
  
_footer:
  enabled:     true
  
_header:
  enabled:     true

_leftside:
  enabled:     true
  
_rightside:
  enabled:     true
