# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  host: http://localhost/nytimes/web/
  webname: Спорт мэдээ - Монголын болон Дэлхий дахины спортын мэдээ мэдээлэл
  domain: sport.mn
  domain_www: www.sport.mn
  feedback_email: batsukhd.mn@gmail.com
  facebook: pages/Firewall-Solution/1406628809597011
  twitter: 
  youtube: 
  pager: 20
  limit: 20
  nb_comment: 20