# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# main
about:
  url:   /aboutus.php
  param: { module: main, action: about }
advertisement:
  url:   /ad.php
  param: { module: main, action: advertisement }
privacy:
  url:   /privacy.php
  param: { module: main, action: privacy }
terms:
  url:   /privacy.php
  param: { module: main, action: terms }
cooperate:
  url:   /cooperate.php
  param: { module: main, action: cooperate }
contact:
  url:   /contactus.php
  param: { module: main, action: contact }
404:
  url:   /404.php
  param: { module: main, action: 404 }

# page
index:
  url:   /i/:categoryRoute.php
  param: { module: page, action: index }
  
show:
  url:   /s/:route.php
  param: { module: page, action: show }

# default rules
homepage:
  url:   /
  param: { module: main, action: home }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module.php
  param: { action: index }

default:
  url:   /:module/:action/*
  
default_error:
  url:   /*
  param: { module: main, action: 404 }